name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet_version: [ '4.7.2', '8.0' ]
        configuration: [ 'Debug', 'Release' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet_version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }}

    - name: Publish artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          **/bin/${{ matrix.configuration }}/
